
#define PIN_ANALOG_SENSOR_SOIL_MOISTURE PIN_A0
#define PIN_ANALOG_SENSOR_LIGHT_INTENSITY PIN_A1
#define PIN_ANALOG_SENSOR_TEMP PIN3

#define PIN_DIGITAL_NAV_MENU 10
#define PIN_DIGITAL_NAV_LEFT 11
#define PIN_DIGITAL_NAV_RIGHT 12

#define DHTPIN PIN2
#define DHTTYPE DHT22

#define PIN_DIGITAL_WATER_PUMP_CTRL 5